server:
  port: 7001
spring:
  application:
    name: config-center
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs/{profile}
          #searchLocations: file:/d:/configs/{profile}
        git:
          uri: https://github.com/lijun516888/sword/tree/master/sword-cloud/sword-cloud-config/src/main/resources
          default-label: master
          force-pull: true
          searchPaths: '{profile}'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}