server:
  port: 6002
spring:
  application:
    name: config-center
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configs/{profile}
        git:
          uri: https://github.com/lijun516888/cloud-config.git
          default-label: master
          force-pull: true
          search-paths: '{profile}'
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.98.64.131:6001/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 39.98.64.131