server:
  port: 8001
spring:
  application:
    name: user-center
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        serviceId: config-center
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6001/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
